# netlify.toml

# Build settings
[build]
  command = "npm run build --prefix app" # The build command for your project
  publish = "app/build"     # The directory containing your built files

# Environment variables
[build.environment]
  NODE_ENV = "production"   # Set NODE_ENV to "production" during the build
  NODE_VERSION = "18.18.0"       # Use Node.js version 14

# Redirects and rewrites (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Add any additional configuration here as needed
# Deploy settings
  [context]
    [context.production]
    MONGODB_URI = "mongodb+srv://santoshadmin:Ubs%401983@mongocluster0.gs6rdav.mongodb.net/smart-resume-builder"
    [context.deploy-preview]
    MONGODB_URI = "mongodb+srv://santoshadmin:Ubs%401983@mongocluster0.gs6rdav.mongodb.net/smart-resume-builder"
  
# Plugins (optional)
# You can enable and configure Netlify plugins here, if needed

# Functions (optional)
# If you're using Netlify Functions, you can configure them here

# Identity (optional)
# If you're using Netlify Identity, you can configure it here

# Asset optimization (optional)
